language: node_js
node_js:
  - "node"
before_install: npm install -g grunt-cli
install: npm install
before_script:
  - npm install -g bower
  - bower install
notifications:
  slack: rti:nB1KzpwxAQ5qi6EC2uydltSx
